#!/usr/bin/env bash
# Very basic interface for pass using wofi

# Get all password files and create an array
CACHE=~/.local/tmp/pass_wofi
seat=seat0

list_passwords() {
    shopt -s nullglob globstar
	cd "$PASSWORD_STORE_DIR" || exit
	pw_list=(**/*.gpg)
	printf '%s\n' "${pw_list[@]%.gpg}" | sort -n

}

prompt='search for passwords...'
SECRET=$(list_passwords | wofi -i --width 700 --lines 20 --height 250 --prompt="${prompt}" --dmenu --cache-file ${CACHE})

# Get password
PASSWD_PASS=$(pass ${SECRET})
# Strip extra lines

IFS=$'\n' read -r PASSWD_PASS <<<"$PASSWD_PASS"
# PASSWD_PASS=(${PASSWD_PASS[*]})

wl-copy -o -s ${seat} "${PASSWD_PASS}"
